# regression testing after changes
# require large memory chap15a,c,d
# chap21 doesn't halt??
# missing, chap6c
regression: lc
	lc chap2a.led
	lc chap2b.led
	lc chap2c.led
	lc chap2d.led
	lc chap2e.led
	lc chap2f.led
	lc chap3.led
	lc chap4a.led
	lc chap4b.led
	lc chap4c.led
	lc chap5.led
	lc chap6a.led
	lc chap6b.led
	lc chap6d.led
	lc chap6e.led
	lc chap6f.led
	lc chap7a.led
	lc chap7b.led
	lc chap7c.led
	lc chap7d.led
	lc chap8a.led
	lc chap8c.led <concordanceInput
	lc chap9.led
	lc chap11.led
	lc chap14.led
	lc chap15b.led
	lc chap16.led
	lc chap17.led <chap17input
	lc chap19a.led
	lc chap19b.led
	lc chap19c.led
	lc chap20a.led
	lc chap20b.led
	lc chap20c.led
	lc chap20d.led
