### Copyright 1993-2015 Timothy A. Budd
###-----------------------------------------------------------------------------
##  This file is part of
### ---     Leda: Multiparadigm Programming Language
###-----------------------------------------------------------------------------
##
##  Leda is free software: you can redistribute it and/or modify it under the
##  terms of the MIT license, see file "COPYING" included in this distribution.
##
###-----------------------------------------------------------------------------
### Title: Makefile
###  Maintainer: Henry G. Weller
###   make
###    Build 'refmanual.pdf'
###-----------------------------------------------------------------------------

refmanual.pdf: cprog.sty grammar.tex  refmanual.tex  std.tex  trouble.tex
	@pdflatex refmanual.tex
	@pdflatex refmanual.tex

###-----------------------------------------------------------------------------
