### -*- mode: makefile -*-
###-----------------------------------------------------------------------------
### Title: Common rules for controlling the build process
###  Maintainer: Henry G. Weller
###-----------------------------------------------------------------------------

###-----------------------------------------------------------------------------
### Message controls
###-----------------------------------------------------------------------------
# Can be reset on the command-line
# e.g. options M= C= B= is equivalent to verbose output

# Supress messages from comands other then compile or build
M = @

# Set compilation message
C = @if [ ! -z "$<" ]; then echo Compiling $<; fi;

# Set build message
B = @if [ ! -z "$@" ]; then echo Building $@; fi;

###-----------------------------------------------------------------------------
### Target build options
###-----------------------------------------------------------------------------

# Build from the the top-level directory
%--top:
	$(MAKE) -C ./$(P_DIR) $*

# Verbose messages
%-v %--verbose:
	$(MAKE) $* M= C= B=

# Time the compilations
%-t %--time:
	$(MAKE) $* M= C=time B=

# Build silently
%-s %--silent:
	$(MAKE) -s --no-print-directory $* 2> build.err

# Redirect output to a log file
%-l %--log:
	$(MAKE) v-$* > build.log 2>&1

# Build the optimised target
%-o %--opt:
	$(MAKE) $* TARGET=opt

# Build the debug target
%-d %--debug:
	$(MAKE) $* TARGET=debug

###---------------------------------------------------------------------
### Functions
###---------------------------------------------------------------------
makeAll = +$(foreach dir, $(1), $(MAKE) -C $(dir) $(2);)

###-----------------------------------------------------------------------------
### Miscellaneous commands
###-----------------------------------------------------------------------------
.PHONY: dirclean clean distclean

dirclean:
	$M rm -f $(GARBAGE) $(TOCLEAN) build.log build.err

clean: dirclean

distclean: clean
	$M rm -rf $(P_DIR)/platforms

###-----------------------------------------------------------------------------
