### -*- mode: makefile -*-
###-----------------------------------------------------------------------------
### Title: General make configuration file
###  Maintainer: Henry G. Weller
###-----------------------------------------------------------------------------

###-----------------------------------------------------------------------------
### Identification and inclusion of the default build environment
###-----------------------------------------------------------------------------
ifndef BUILDENV
   BUILDENV=$(BUILDENV_$(shell uname -s))
   BUILDENV_Linux=linux
   BUILDENV_HP-UX=hpux
   BUILDENV_SunOS=sun
endif

include $(P_DIR)/Make/Makefile.config.$(BUILDENV)

###-----------------------------------------------------------------------------
### Set directories and general macros
###-----------------------------------------------------------------------------
ifndef DIR
    # The cd ./ in FULLDIR is for a corner case where . is a symbolic link
    # At least with bash (not sure with other shells), pwd returns me
    # the symbolic link path (as for BASEDIR), rather than the physical path
    # So this is necessary for the substitution to happen correctly. Ugh!
    BASEDIR=    $(shell cd ./$(P_DIR); pwd)
    FULLDIR=	$(shell cd ./; pwd)
    DIR=        $(subst $(BASEDIR),,$(FULLDIR))
endif

OBJROOT=        $(P_DIR)/platforms/$(BUILDENV)/$(TARGET)
OBJDIR=		$(OBJROOT)$(DIR)
INCDIR=		$(P_DIR)/platforms/$(BUILDENV)/include
OBJECTS=	$(SOURCES:%=$(OBJDIR)/%.o)
OBJLIBRARY=	$(LIBRARY:%=$(OBJROOT)/%)
OBJDRIVER=	$(DRIVER:%=$(OBJROOT)/%)
OBJEXE=		$(OBJDIR)/$(PRODUCT)
OBJLIBRARIES=	$(LIBRARIES:%.a=$(OBJROOT)/%.a)
OBJLIBDEP=	$(filter %.a, $(OBJLIBRARIES))
GARBAGE=	*~ *.bak

###-----------------------------------------------------------------------------
### Compilation flags
###-----------------------------------------------------------------------------
DEFINES_debug=-DDEBUG
DEFINES_opt=-DNDEBUG
LDFLAGS_debug=-g

CPPFLAGS=	$(DEFINES) $(DEFINES_$(BUILDENV))	\
		$(DEFINES_all) $(DEFINES_$(TARGET))	\
		$(INCLUDES)
CFLAGS=		$(CPPFLAGS) $(CFLAGS_$(TARGET)) $(CFLAGS_all)
CXXFLAGS=	$(CPPFLAGS) $(CXXFLAGS_$(TARGET)) $(CXXFLAGS_all)
LDFLAGS=	$(LDFLAGS_$(TARGET)) $(LDFLAGS_all)

###-----------------------------------------------------------------------------
